### ISSUE TITLE
Quick Setup

### ISSUE THREAD

**Issue by enateur** [ofekmiz/Habitica-Pomodoro-SiteKeeper#108]
Hi, I wanted to know if there's a way to access Quick Setup without having to do a whole Pomodoro set. Currently, the Quick Setup option only shows up on the menu after you've completed an entire Pomodoro set, and after the long break. Sometimes I need to set a long break for lunch, and it doesn't always neatly fall after 4 Pomodoros. If I have the option to access Quick Setup at any time, it would solve this issue for me. Otherwise I love the extension 😊

**Comment by ofekmiz** [comment]
Hi @enateur, there is no way to enter Quick Setup during a session since it encourages cheating.
I can suggest another solution for your situation: 
In the Settings enable "start breaks manually" and "skip to break button", this way you can control when you start the break, so you can go for lunch and start the short break when you are done. A better solution would be to set less pomodoros in a set, maybe only 1 or 2 with a shorter long break if you are not sure when you go for lunch, and take a long break manually when you need it. 

Go over the full settings and customize it as you wish, 4 pomodoros is just my default recommendation :)

**Comment by enateur** [comment]
> Hi @enateur, there is no way to enter Quick Setup during a session since it encourages cheating. I can suggest another solution for your situation: In the Settings enable "start breaks manually" and "skip to break button", this way you can control when you start the break, so you can go for lunch and start the short break when you are done. A better solution would be to set less pomodoros in a set, maybe only 1 or 2 with a shorter long break if you are not sure when you go for lunch, and take a long break manually when you need it.
> 
> Go over the full settings and customize it as you wish, 4 pomodoros is just my default recommendation :)

Hi, thank you for that suggestion. I will try that today and see how it works for me. Thank you!
