### ISSUE TITLE
I don't want the website preview to load. I want a page that's NOT the website to tell me I'm blocked from accessing the page

### ISSUE THREAD

**Issue by SaSaSaSam** [ofekmiz/Habitica-Pomodoro-SiteKeeper#14]
Look at the leechblock extension to have a better idea of what I'm talking about

**Comment by ofekmiz** [comment]
Hey, Thanks for the feedback.

Can you give me more details? What do you mean by "website preview" and why do you want it to be on a different page? (why is it better?)
What you want can be done but it's a lot of work so I want to make sure I understand why is it better for you this way :)

If the problem is that you can see the website below the black overlay I can add an option to make the overlay completely black and it would be much easier for me to implement, is this solution good for what you need?
Here is an example:
![image](https://user-images.githubusercontent.com/39601942/83568480-cb3a6500-a52b-11ea-9f6c-de0d63f872c8.png)

**Comment by SaSaSaSam** [comment]
The example is exactly what I need.
:))

**Comment by SaSaSaSam** [comment]
I would like the timer to intercept right before the page loads.

**Comment by ofekmiz** [comment]
Working on it :) I will add it to the next update

**Comment by Kaizen543** [comment]
I noticed that there is a delay from the page loading and the warning icon showing up. Not a deal breaker but its an issue still. Though I noticed that if I left the timer showing up for 1 min it removes by itself but goes back in after a few sec. Might want to take a look at that too

**Comment by Kaizen543** [comment]
Its alright, the delay isnt much of an issue to be honest and I know that the server delay is normal. I'm mainly concerned about the mute bug since it destroys the feature which is a bummer since it is a wonderful feature.
    On Saturday, 22 August 2020, 03:02:35 am GMT+8, OfeX <notifications@github.com> wrote:  
 
 


@Kaizen543, unfortunately, I can't remove the delay because it takes some time to communicate with the Habitica server and check if the user has enough coins. sorry about that.

@SaSaSaSam this option should remove the opacity in the next update:

I can't make the "Pay to pass" block appear immediately for now since it takes time to communicate with the Habitica server. But the Pomodoro Timer block should appear immediately.
