### ISSUE TITLE
Notification Volume 

### ISSUE THREAD

**Issue by meepetpet** [ofekmiz/Habitica-Pomodoro-SiteKeeper#19]
Hi!
The notification sound is really, really loud, it scares me everytime haha
 I work on mac and can't adjust the volume of google chrome or any application individually

hope a kind person can help solving this problem
thank you so much

**Comment by ofekmiz** [comment]
Hi,
I'll try to add volume control for the next update.
For now maybe this can help :)
https://github.com/kyleneideck/BackgroundMusic

**Comment by jamieenby** [comment]
**I agree** because my autism was extremely painful and might be suffering for some time I had my headphones in and it really really really hurt please do update soon for now i can turn the sound off and await your brilliance in making it autism-friendly, thanks for what you have done so far awesome stuff

**Comment by meepetpet** [comment]
Thank you so much for working on this feature! I tried background music and other things that didn't work, unfortunately

**Comment by ofekmiz** [comment]
@meepetpet  @jamieenby  Volume and new sounds are added in the next update (5.75) !
