### ISSUE TITLE
Auto Next Pomodoro

### ISSUE THREAD

**Issue by MrsKatUSMC** [ofekmiz/Habitica-Pomodoro-SiteKeeper#22]
Sometimes during a "break" I'll go to take care of one of my kids... By the time I get back the break will have ended and the pomodoro was broken, so I have to start all 4 over again.  When you hear a toddler wake up or a teen calls for your help, you dont always think "I better hit the triangle to start the pomodoro even though my break is only at 0:30/5:00...", you just jump up and go see what is going on!

The settings give you the option to let the computer automatically/manually start the break...  The only reason I ever get to utilize a break is because I have it set to manually start the break!  I appreciate that feature a LOT!

Please make a checkbox that will let the computer automatically/manually start the next pomodoro.

**Comment by ofekmiz** [comment]
Hi @MrsKatUSMC :) 

Usually starting a pomodoro automatically after a break is not "best practice", because it makes it easy to "cheat" and cut some of the work time during the break. And if you use Habitica integration that means you can get a reward without doing the work.

On the other hand, of course you want to have a relaxed break without worrying about breaking the pomodoro streak. 
That's why you have "Break Extension" option: it gives you some extra time to come back from the short break. 
If you know that you usually need to extend the break for "toddler reasons", I recommend setting a long time for Break Extension. Just make sure you are not abusing the break extension and press the tomato as soon as you return to work.

Hope it helps,
If you still prefer to have a checkbox "automatically/manually start the next pomodoro" let me know and I will try to add it in future updates.

**Comment by MrsKatUSMC** [comment]
No matter what, it's a great extension!  I was just looking up habitica extensions...  I had no idea what a pomodoro is, but I'm really happy I tried it!!! <3 

I dont think I explained my concept well enough.

With the "Manual Break" you have to click the triangle to START the break.
With the "Manual Pomodoro" I'd like to have to click the triangle to START the next pomodoro.
(exactly how the manual break works)

I dont want it to start rolling the "work" clock.  You're right, that is counter productive and cheating!
I just want it to LOCK me out of the websites when the break extension ends, and NOT lose the streak!!!  
AND therefore I dont lose the LONG BREAK!!!  

Longer Extensions:
I did try making the break extension longer... and I was displeased with my own lack of discipline in my current state of medical isolation.  I havn't left my house or interacted with my family since March 13th 2020 when the doctor's gave my son medical directions to have "no one in or out of the house" for his safety due to 27 Medical Diagnoses including heart, respiratory, and immunity problems among others.  No public school, No grocery stores, No family.  Virtual ONLY!  Zero-Contact Groceries Only!  Even my husband is not allowed in our home because of these Doctor's orders... he's living with coworkers, which Sucks...  He "temporarily" moved out in June.  I'm not happy to admit that when I finally have the chance to be unproductive, I got sucked into the break extension and kept using it for longer than I should have.  I absolutely like that each person can set that longer or shorter for their own needs.  Having a 2min break extension is barely enough to finish writing a sentence or watching a video, which is perfect FOR ME!  Any longer, and I regrettably cave to my yearning for social interaction with Adults.  My lack of discipline is appalling.  (I've got Perfect Control of my weight, exercise, responsibilities, chores, etc... but me & the 3 kids REALLY miss hanging out with friends and family...)

Lost Long Breaks:
I was mid break and my son's gastrostomy tube alarm went off...  Myself and both teens go on alert when my little's boys medical devices make sounds, it's just instinct at this point!   I spent too much time taking care of his medical needs, and I LOST the whole streak... So then the extension put me at 0/4!  It took me 7 out of 4 pomodoros to get a long break that day, last week.
I finally turned the extension off because I NEEDED A BREAK!... which is the ultimate form of counter productive! ... it just caused more frustration.  That's the same day that I wrote the request because similar scenarios had already happened multiple times.

I use this extension to block unproductive websites, and I look forward to wasting time during the 30 minute break!... but if I never GET to take the 30 minute break because I was paying attention to my Kids, and not the computer... I end up just turning it off!

I KNOW IT'S NOT YOUR FAULT THAT I'M STRUGGLING!  It's not my son's, not his doctors, not anyone's fault that my only Adult time is Virtual... and it's definitely only MY FAULT that I abuse any time I can get to be with adults After the kids schoolday!

... I really think having to complete 4 Pomodoros before a half hour break was helping me every time I COULD achieve it!
...but it could help me a lot more if I'm ALWAYS ABLE to achieve it!
I would exceedingly appreciate it if you made the Pomodoros work the same way the Breaks work, but I will fully understand if you decide Not to! <3

**Comment by ofekmiz** [comment]
Hi @MrsKatUSMC  
Sounds like a challenging time for you, stay strong!

I will add the option you requested because it is not very complicated, but I would still recommend thinking of a more effective solution - running the next Pomodoro manually it is basically like saying there is an unlimited break extension and it may cause a lack of productivity.

Options I can recommend until the option is added:

1. If you click on the small clock-shaped icon next to the tomato it will open the "Quick Setup" window, where you have the option to take a single break * manually ** for any length you want. And when the break is over you will start again.

2. It's nobody's fault we are strugelling, that's how our brain works, otherwise we would not have needed the Pomodoro technique at all. But in order to get better, no matter how many options there are, you still need to get back from the break and start working. Maybe 4 sets of 25 minutes is not so suitable for you, try to play with the times, I personally prefer 3 sets of 35 minutes with 8 minutes break, and a long break of 40 minutes. It's very individual.

Good Luck!

**Comment by MrsKatUSMC** [comment]
Thank you for the update, and for the alternative recommendations!

I'm very happy I found your program, and I will try your other suggestions to find the best way for it to help! <3

**Comment by MrsKatUSMC** [comment]
Yesterday was a horrible day. and a Huge Success!  I missed the timer alarm Twice, but the new option encouraged me to regain my composure and pull back into the next work session.  I cant wait to check my daily journal at the end of the week to see how much this helps me improve.
Thank You So Much For Making This Extension!!!
