### ISSUE TITLE
Sometimes it takes a really long time to ask to unblock and allows browsing during that time

### ISSUE THREAD

**Issue by citrusella** [ofekmiz/Habitica-Pomodoro-SiteKeeper#4]
Right now I only have Twitter on the block list, but oftentimes lately I'll visit it and it will wait several minutes to ask if I want to pay, during which I can browse the site as if it's unblocked. ~~Once it finally asks (assuming it *does* ask before I leave), the time I was on the site appears to have been included in the time it counts down to--for instance I just paid to unblock Twitter when it asked most recently, after I'd been on it for several minutes, and it says I have 16:53 remaining to use it when the unblock length is 30 minutes.~~

Sometimes it doesn't ask at all before I've exhausted my interest in checking the site--thus translating to a free use of it as if vacation mode is on (it's not).

Starting a pomodoro does properly immediately block the site, though.

I don't know if something on my end could be causing this, but it seems to have started out of the blue with no deliberate changes to my browser or any other extensions...

**Comment by ofekmiz** [comment]
Hi :)

Just to make sure, 16:53 is the remaining or the time that appears in the blocked list? (if it appears on the block list it means that the site is open until  the hour 16:53, and not open for 16.53 minutes)

When the site is getting blocked, do you get this alert during your visit on twitter?
https://ofekm.tinytake.com/tt/MzkyMzMzNF8xMjAzNTc0Mw

Since it started out of the blue please try to reinstall the extension from the chrome app store. Anyway, I am working on improving the block system but it takes time :)

**Comment by citrusella** [comment]
In regards to the block time: ...D'oh. I misread how the time worked. So ignore that part. Whoops. :-/

I do get that window but oftentimes only after several minutes of using the site without the extension stopping me, instead of right when I open it.

I guess I'm making a to-do to reinstall, then.

**Comment by ofekmiz** [comment]
Hi :)
@citrusella
Just to make sure, 16:53 is the remaining or the time that appears in the blocked list? (if it appears on the block list it means that the site is open until  the hour 16:53, and not open for 16.53 minutes)

When the site is getting blocked, do you get this alert during your visit on twitter?
https://ofekm.tinytake.com/tt/MzkyMzMzNF8xMjAzNTc0Mw

Since it started out of the blue please try to reinstall the extension from the chrome app store. Anyway, I am working on improving the block system but it takes time :)

**Comment by ofekmiz** [comment]
> In regards to the block time: ...D'oh. I misread how the time worked. So ignore that part. Whoops. :-/
> 
> I do get that window but oftentimes only after several minutes of using the site without the extension stopping me, instead of right when I open it.
> 
> I guess I'm making a to-do to reinstall, then.

If the problem persists let me know.

**Comment by citrusella** [comment]
Reinstalling didn't seem to fix it, *but* I added other sites and those seem to work fine.

My only guess is that Twitter is more taxing on my computer so the extension takes a bit to respond. (A family member is theorizing my hard drive might be slowly dying, so it's possible performance has gradually gotten worse since I first got the extension and I just didn't notice a specific change because it's been happening so slowly.) If there's any possibility of it being something else, I wouldn't know what to consider...

**Comment by ofekmiz** [comment]
Thanks, I'll see what I can do :)
Maybe the improved block system will solve it, but it will take some time...

**Comment by ofekmiz** [comment]
I think it should be fixed now. please update the extension try again, let me know  if it works.
