### ISSUE TITLE
/bug --  pomodoro doesn't run automatically

### ISSUE THREAD

**Issue by MrKebab362** [ofekmiz/Habitica-Pomodoro-SiteKeeper#54]
When I finish my break, it goes to an extension period which I can't seem to remove, and then it doesn't go to the work timer automatically, and i have to manually click it. I often forget about it and end up not starting the timer.

**Comment by ofekmiz** [comment]
Hi @MrKebab362
Break Extension purpose is to give you a bit of extra break time that allows you to come back, get ready and start a new working session. Since this is extra time (you can set it to 0 if you want in the settings). it is recommended not to take advantage of it to the end and start a new Pomodoro session as soon as possible by clicking on the pomodoro character. 

Starting a new working session is manual to make sure you came back from the break.
Many asked for a solution when they are in "deep focus" and keep working after the time ended or forget to start it manually, so I will add an option to get bonus gold for "deep focus", and an option to start a working session automatically for those who really want to (though I won't recommend it ) in the future.

Here is the recommended workflow:
![image](https://user-images.githubusercontent.com/39601942/114080974-aeda2800-98b4-11eb-9c8a-438597b3492a.png)

hope it helps!

**Comment by MrKebab362** [comment]
Thanks so much
